### ISSUE TITLE
Problem parsing Windows line endings

### ISSUE THREAD

**Issue by JoshSchreuder** [jgranstrom/sass-extract#16]
See attached test case (sorry about the ZIP, Github doesn't support .scss directly):
[test.zip](https://github.com/jgranstrom/sass-extract/files/1328436/test.zip)

On Windows, files with multiple lines can't be parsed by `scss-parser`.

```
" (1:16)d rejection Error: Can't handle character: "
    at InputStream.err (C:\myproject\node_modules\scss-parser\dist\input-stream.js:122:13)
    at Object.err (C:\myproject\node_modules\scss-parser\dist\input-stream.js:161:20)
    at TokenStream.err (C:\myproject\node_modules\scss-parser\dist\token-stream.js:297:40)
    at TokenStream.read_next (C:\myproject\node_modules\scss-parser\dist\token-stream.js:352:12)
    at TokenStream.peek (C:\myproject\node_modules\scss-parser\dist\token-stream.js:248:26)
    at TokenStream.eof (C:\myproject\node_modules\scss-parser\dist\token-stream.js:282:26)
    at Object.eof (C:\myproject\node_modules\scss-parser\dist\token-stream.js:631:16)
    at Parser.parse_stylesheet (C:\myproject\node_modules\scss-parser\dist\parse.js:266:27)
    at module.exports (C:\myproject\node_modules\scss-parser\dist\parse.js:748:17)
    at parse (C:\myproject\node_modules\scss-parser\dist\index.js:27:10)
    at parseDeclarations (C:\myproject\node_modules\sass-extract\lib\parse.js:131:35)
    at processFile (C:\myproject\node_modules\sass-extract\lib\process.js:25:51)
    at C:\myproject\node_modules\sass-extract\lib\process.js:58:29
    at Array.map (<anonymous>)
    at processFiles (C:\myproject\node_modules\sass-extract\lib\process.js:57:22)
    at C:\myproject\node_modules\sass-extract\lib\extract.js:126:49
```

If I convert the line endings to `lf` with [`eol`](https://www.npmjs.com/package/eol) it works correctly.

I tried passing the [`linefeed`](https://github.com/sass/node-sass#linefeed--v300) option in to render options, but it didn't seem to have any effect.

**Comment by jgranstrom** [comment]
@JoshSchreuder thank you for the report. I will add additional test cases for Windows and a fix for the line endings in the next patch, probably before this weekend.

**Comment by JoshSchreuder** [comment]
No worries, thanks for the handy tool, I look forward to being able to use it properly 😄

**Comment by Saturate** [comment]
I'm also encountering this issue, a shame as it's working for me non-windows systems :-)

**Comment by jgranstrom** [comment]
@JoshSchreuder @Saturate we are looking at replacing the parser with another option since there is issues with parsing varargs with that as well. Will make sure we get this fixed in the process. I haven't been able to work on this the last few weeks due to some other things going on, but I will make some efforts on this tonight and hopefully have a release out this week that fixes all the open issues.

**Comment by Saturate** [comment]
@jgranstrom that's awesome, thanks for your work! :-)

**Comment by jgranstrom** [comment]
@JoshSchreuder @Saturate the latest [2.0.0 release](https://github.com/jgranstrom/sass-extract/releases/tag/v2.0.0) should take care of the mentioned compatibility issues. The [automated tests](https://ci.appveyor.com/project/jgranstrom/sass-extract) for windows are showing green light for both unix and windows style line endings. Please get back to me if there's still any issues on the windows platform. Thank you for the detailed report!
