### ISSUE TITLE
Problem parsing IE hacks

### ISSUE THREAD

**Issue by JoshSchreuder** [jgranstrom/sass-extract#17]
Found another issue, and I realise this is not really on you, but rather in `scss-parser` but it doesn't seem to be open source.

If you have a style such as

```scss
&:focus {
   outline: 0;
   outline: thin dotted \9; /* IE6-9 */
}
```

`scss-parser` will throw an error trying to parse the `\`:

```
Unhandled rejection Error: Can't handle character: "\" (39:25)
    at InputStream.err (C:\myproj\node_modules\scss-parser\dist\input-stream.js:122:13)
    at Object.err (C:\myproj\node_modules\scss-parser\dist\input-stream.js:161:20)
    at TokenStream.err (C:\myproj\node_modules\scss-parser\dist\token-stream.js:297:40)
    at TokenStream.read_next (C:\myproj\node_modules\scss-parser\dist\token-stream.js:352:12)
    at TokenStream.peek (C:\myproj\node_modules\scss-parser\dist\token-stream.js:254:27)
    at Object.peek (C:\myproj\node_modules\scss-parser\dist\token-stream.js:625:21)
    at C:\myproj\node_modules\scss-parser\dist\parse.js:90:30
    at Array.reduce (<anonymous>)
    at Parser.is_type (C:\myproj\node_modules\scss-parser\dist\parse.js:89:21)
    at Parser.is_punctuation (C:\myproj\node_modules\scss-parser\dist\parse.js:128:27)
    at Parser.is_interpolation (C:\myproj\node_modules\scss-parser\dist\parse.js:176:19)
    at C:\myproj\node_modules\scss-parser\dist\parse.js:426:20
    at Parser.maybe_function (C:\myproj\node_modules\scss-parser\dist\parse.js:609:14)
    at Parser.parse_atom (C:\myproj\node_modules\scss-parser\dist\parse.js:420:19)
    at Parser.parse_node (C:\myproj\node_modules\scss-parser\dist\parse.js:353:25)
    at Parser.parse_block (C:\myproj\node_modules\scss-parser\dist\parse.js:539:25)
```

For what it's worth I hate these dodgy style hacks but I didn't write it 😄 

Replacing this token with an empty string before calling ` (0, _scssParser.parse)` in `parse.js` makes the parser happy again

**Comment by jgranstrom** [comment]
This is fixed in the latest [2.0.0 release](https://github.com/jgranstrom/sass-extract/releases/tag/v2.0.0). Thank you for reporting it!
