### ISSUE TITLE
Raw css imports are not supported

### ISSUE THREAD

**Issue by gglnx** [jgranstrom/sass-extract#32]
Hello,

we're using raw css imports (https://github.com/sass/libsass/pull/754), but sass-extract fails on them, because the custom imported always adds a `.scss` before trying to import the file.

    Error: Can not determine imported file for url 'sanitize.css/sanitize.scss' imported in src/stylesheets/main.scss
        at Object.module.exports.renderSync (node_modules/node-sass/lib/index.js:439:16)
        at extractSync (node_modules/sass-extract/lib/extract.js:171:22)
        at Object.renderSync (node_modules/sass-extract/lib/render.js:46:44)
        at Object.<anonymous> (sass-test.js:7:34)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.runMain (module.js:605:10)
        at run (bootstrap_node.js:427:7)
        at startup (bootstrap_node.js:151:9)
        at bootstrap_node.js:542:3

Thank you!

**Comment by bencergazda** [comment]
@jgranstrom This would be relatively easy to fix, or rather try to find the file according to the original import resolution of Sass. This is described in https://jonathantneal.github.io/sass-import-resolve/#resolve-algorithm, and already implemented in `sass-loader`'s [importsToResolve()](https://github.com/webpack-contrib/sass-loader/blob/master/lib/importsToResolve.js). I can do the task if needed.
